# common.py
#
# Area for configuration variables and commonly-used values
# David Lister
# July 2023
#

# SRS830
SRS830_CAPTURE_TIME_S = 3  #s
SRS830_STATE_INIT = "SRS830_STATE_INIT"
SRS830_STATE_WAITING_FOR_SERIAL_PORT = "SRS830_STATE_WAITING_FOR_SERIAL_PORT"
SRS830_STATE_RUN_CAPTURING_DATA = "SRS830_STATE_RUN_CAPTURING_DATA"
SRS830_STATE_RUN_TRANSFERRING_DATA = "SRS830_STATE_RUN_TRANSFERRING_DATA"
SRS830_STATE_RUN_ENDING = "SRS830_STATE_RUN_ENDING"
